export const ActionTypes = {
    //friends
    ADD_FRIEND: "ADD_FRIEND",
    REMOVE_FRIEND: "REMOVE_FRIEND",
    INVITE_FRIEND_WATCH: "INVITE_FRIEND_WATCH",

    //movies
    ADD_MOVIE_WISHLIST: "ADD_MOVIE_WISHLIST",
    REMOVE_MOVIE_WISHLIST: "REMOVE_MOVIE_WISHLIST",
    ADD_MOVIE_WATCHED: "ADD_MOVIE_WATCHED",
    REMOVE_MOVIE_WATCHED: "REMOVE_MOVIE_WATCHED",
    ADD_MOVIE_FAVORITE: "ADD_MOVIE_FAVORITE",
    REMOVE_MOVIE_FAVORITE: "REMOVE_MOVIE_FAVORITE",
};
